ALTER TABLE "Category" ADD COLUMN "deletedAt" TIMESTAMP(3);
ALTER TABLE "AppTemplate" ADD COLUMN "deletedAt" TIMESTAMP(3);
ALTER TABLE "App" ADD COLUMN "deletedAt" TIMESTAMP(3);
ALTER TABLE "Duration" ADD COLUMN "deletedAt" TIMESTAMP(3);
ALTER TABLE "Account" ADD COLUMN "deletedAt" TIMESTAMP(3);
ALTER TABLE "SubAccount" ADD COLUMN "deletedAt" TIMESTAMP(3);
